version: "3.8"

services:
  blogger-notifier:
    build: .
    container_name: blogger-bot
    restart: unless-stopped
    env_file:
      - stack.env
    volumes:
      - /volume1/docker/blogger_data:/app/data:rw